Measures was an exercise for the course Test logiciel (= Software testing) at Nantes University in the autumn 2022. The exercise consisted of reviewing and updating tests, learning to use JaCoCo for code coverage and PITest for mutation testing.

= Measures

Bibliothèque pour la représentation et la conversion d'unités de mesures physiques (volumes et longueurs).

Unités de volume prises en compte (classe abstraite `Volume`) :

- gallon (classe `Gallon`),
- litre (classe `Litre`).

Unités de longueur prises en compte (classe abstraite `Length`) :

- pied (classe `Foot`),
- pouce (classe `Inch`),
- mètre (classe `Meter`).

== Compilation et test

Utiliser Maven :

```
mvn package
```

== Exemples


On crée une quantité avec l'unité de son choix, par exemple en pieds :

```java
Foot foot = new Foot(1);
```

Puis on peut convertir cette distance en une autre unité, par exemple en mètres ou en pouces, avec les méthodes dédiées :

```java
Meter m = foot.toMeter();
Inch i = foot.toInch();
```
